name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - run: pip install -r requirements.txt
    
    - name: Lint code
      run: |
        pip install flake8  # Install flake8 for linting
        flake8 app_dir tests  # Lint the app and tests directories

    - name: Format code
      run: |
        pip install black  
        black --check app_dir tests 

    - name: Type check
      run: |
        pip install mypy  
        mypy app_dir  

    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:./app_dir  # Add app_dir to PYTHONPATH
        pytest 